### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by shortthefomo** [technotip/flagnames#1]
<img width="724" alt="Screen Shot 2022-10-17 at 20 26 46" src="https://user-images.githubusercontent.com/508629/196302039-e08884e0-1b99-436b-aa76-9ed3949785ad.png">

not sure what ive provided incorrectly here.

**Comment by technotip** [comment]
The script only had support for AccountRoot and RippleState flags. Added SignerList. Thank you.

I think SignerList has only 1 flag? https://xrpl.org/signerlist.html#signerlist-flags

**Comment by shortthefomo** [comment]
wonderful thank you!
